# Day-to-day evolution of supply and demand
Module for simulating ridesourcing evolution, including pooled rides

Contribution by Arjan de Ruijter - a.j.f.deruijter@tudelft.nl

In [1]:
%load_ext autoreload
%autoreload 2
import os, sys # add MaaSSim and MaaSSim/MaaSSim to path (not needed if already in path)
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
from MaaSSim.utils import save_config, get_config, load_G, generate_demand, initialize_df, empty_series, \
    slice_space, test_space, read_requests_csv
from MaaSSim.maassim import Simulator
from MaaSSim.data_structures import structures as inData
from MaaSSim.d2d_sim import *
from MaaSSim.d2d_demand import *
from MaaSSim.d2d_supply import *
from MaaSSim.d2d_shared import prep_shared_rides
from MaaSSim.decisions import dummy_False

In [3]:
import pandas as pd
import zipfile
import logging
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.lines import Line2D
import numpy as np
import random
import ExMAS
plt.style.use('ggplot')
np.random.seed(0)
random.seed(0)

In [4]:
# Load config
params = get_config('../../data/config/delft.json')  # load configuration
params.paths.albatross = '../../data/albatross'

In [5]:
# Experiment replications and number of threads to be used
params.parallel.nReplications = 1
params.parallel.nThread = 1

# Main experimental settings
params.nP = 500 # travellers
params.nV = 20 # drivers
params.nD = 1 # days
params.simTime = 4 # hours

In [6]:
# Other day-to-day settings
params.evol.drivers.kappa = 0.2 # learning weight (supply-side)
params.evol.drivers.res_wage.mean = 25 #euros/h
params.evol.drivers.gini = 0.35 # gini coefficient used to establish sigma parameter of log-norm distribution of res wage
params.evol.drivers.init_inc_ratio = 1 #expected income of informed drivers at start of sim as ratio of res wage

params.evol.drivers.inform.prob_start = 1 # probability of being informed at start of sim
params.evol.drivers.inform.beta = 0.1 # information transmission rate
params.evol.drivers.inform.std_fact = 0.5 # multiplier of the standard deviation of experienced income used in signal

params.evol.drivers.regist.prob_start = 1 # probability of being registered if informed at start of sim
params.evol.drivers.regist.beta = 0.2 # registration choice model parameter
params.evol.drivers.regist.cost_comp = 20 # daily share of registration costs (euros)
params.evol.drivers.regist.samp = 0.5 # probability of making (de)regist decision
params.evol.drivers.regist.min_work_exp = 0 # Working experience required before deregistration is possible
params.evol.drivers.regist.min_days = 5 # Minimum number of registered days before driver can deregister

params.evol.drivers.particip.beta = 0.1 # participation choice model parameter
params.evol.drivers.particip.probabilistic = True # stochasticity in participation choice

params.evol.travellers.inform.prob_start = 1 # probability that traveller is informed at start of sim
params.evol.travellers.inform.beta = 0.1 # information transmission rate (demand-side)
params.evol.travellers.inform.start_wait = 0 # expected waiting time at start of simulation
params.evol.travellers.inform.std_fact = 0.5 # multiplier of the standard deviation of experienced waiting time used in signal
params.evol.travellers.reject_penalty = 30 * 60 # seconds
params.evol.travellers.kappa = 0.2 # learning weight (demand-side)
params.evol.travellers.min_prob = 0.05 # filtering criterion, when probability is lower when waiting time is zero, never consider RS

params.evol.travellers.mode_pref.mean_vot = 10 # Mean VoT in euro/h
params.evol.travellers.mode_pref.access_multip = 2 # Multiplier of access time compared to in-vehicle time
params.evol.travellers.mode_pref.wait_multip = 2.5 # Multiplier of waiting time compared to in-vehicle time
params.evol.travellers.mode_pref.bike_multip = 2 # Multiplier of biking time compared to in-vehicle time
params.evol.travellers.mode_pref.beta_cost = -0.1592 # util/euro
params.evol.travellers.mode_pref.transfer_pen = 5 * 60 # seconds, to be added to IVT for each transfer
params.evol.travellers.mode_pref.ASC_car = 0 # util, rel to bike
params.evol.travellers.mode_pref.ASC_rs = 0
params.evol.travellers.mode_pref.ASC_pt =  0
params.evol.travellers.mode_pref.ASC_car_sd = 0 # standard deviation in ASCs
params.evol.travellers.mode_pref.ASC_rs_sd = 0
params.evol.travellers.mode_pref.ASC_pt_sd = 0
params.evol.travellers.mode_pref.ASC_bike_sd = 0
params.evol.travellers.mode_pref.gini = params.evol.drivers.gini

# Financial settings
params.platforms.base_fare = 1 #euro
params.platforms.fare = 0 #euro/km
params.platforms.min_fare = 0 # euro
params.platforms.comm_rate = 0.05 #rate
params.drivers.fuel_costs = 0.25 #euro/km

# Properties alternative modes
params.alt_modes.pt.option = False
params.alt_modes.pt.base_fare = 0.99 # euro
params.alt_modes.pt.km_fare = 0.174 # euro/km
params.alt_modes.car.km_cost = 0.5 # euro/km
params.alt_modes.car.diff_parking = True # different parking tariffs in city
params.alt_modes.car.park_cost = 7.5 # euro
params.alt_modes.car.park_cost_center = 15 # euro
params.alt_modes.car.access_time = 10 * 60 # s
params.speeds.bike = (1/2.5) * params.speeds.ride # m/s

# Regulation
params.platforms.reg_cap = np.inf # registration cap
params.platforms.ptcp_cap = np.inf # daily participation cap

# Demand settings
# params.demand_structure.origins_dispertion = -0.0003
# params.demand_structure.destinations_dispertion = -0.0003
params.dist_threshold_min = 2000 # min dist
# params.dist_threshold = 100000 # max dist

# Start time
# params.t0 = pd.Timestamp.now()
params.t0 = pd.Timestamp(2021, 11, 1, 9)

In [7]:
# Pooling settings
params.shareability.offered = True
params.shareability.avg_speed = params.speeds.ride
params.shareability.min_discount = 0.5
params.shareability.add_discount = 0.0
params.shareability.shared_discount = params.shareability.min_discount
params.shareability.delay_value = 1
params.shareability.WtS = 1.1 # Willingness to share
params.shareability.price = 1.5 #eur/km
params.shareability.VoT = 0.0035 #eur/s
params.shareability.matching_obj = 'u_pax' #minimize VHT for vehicles
params.shareability.pax_delay = 0
params.shareability.horizon = 600
params.shareability.max_degree = 2
params.shareability.nP = params.nP
params.shareability.share = 1
params.shareability.without_matching = True

In [8]:
inData = load_G(inData, params, stats=True, set_t=False)  # download graph for the 'params.city' and calc the skim matrices
if params.alt_modes.car.diff_parking:
    inData = diff_parking(inData) # determine which nodes are in center

In [9]:
inData = generate_demand(inData, params, avg_speed = True)

In [10]:
# Load processed Albatross file, the OTP result, and compute PT fares
# inData = load_albatross_proc(inData, params, avg_speed = True)
# inData.requests = inData.requests.drop(['orig_geo', 'dest_geo', 'origin_y', 'origin_x', 'destination_y', 'destination_x', 'time'], axis = 1)
# inData.pt_itinerary = load_OTP_result(params)
# inData = consist_OTP_alba(inData, params)

In [11]:
# Prepare supply and demand attributes
inData.passengers = prefs_travs(inData, params)
all_pax = mode_filter(inData, params)
inData.passengers = all_pax[all_pax.mode_choice == "day-to-day"]
inData.requests = inData.requests[inData.requests.pax_id.isin(inData.passengers.index)]
if params.alt_modes.pt.option:
    inData.pt_itinerary = inData.pt_itinerary[inData.pt_itinerary.pax_id.isin(inData.passengers.index)]
    inData.passengers.reset_index(drop=True, inplace=True)
    inData.requests.reset_index(drop=True, inplace=True)
    inData.pt_itinerary.reset_index(drop=True, inplace=True)
inData.requests['pax_id'] = inData.requests.index
inData.pt_itinerary['pax_id'] = inData.pt_itinerary.index
inData.passengers['informed'] = np.random.rand(len(inData.passengers)) < params.evol.travellers.inform.prob_start
inData.passengers['expected_wait'] = params.evol.travellers.inform.start_wait
inData.passengers['expected_wait_pool'] = params.evol.travellers.inform.start_wait
inData.passengers['expected_pool_discount'] = params.shareability.min_discount
inData.passengers['expected_pool_delay'] = 0
fixed_supply = generate_vehicles_d2d(inData, params)
inData.vehicles = fixed_supply.copy()
inData.vehicles.platform = inData.vehicles.apply(lambda x: 0, axis = 1)
inData.passengers.platforms = inData.passengers.apply(lambda x: [0], axis = 1)
inData.requests['platform'] = inData.requests.apply(lambda row: inData.passengers.loc[row.name].platforms[0], axis = 1) 
inData.platforms = pd.concat([inData.platforms,pd.DataFrame(columns=['base_fare','comm_rate','min_fare'])])
inData.platforms = initialize_df(inData.platforms)
inData.platforms.loc[0]=[params.platforms.fare,'Uber',30,params.platforms.base_fare,params.platforms.comm_rate,params.platforms.min_fare,]

In [12]:
inData = ExMAS.main(inData, params.shareability, plot=False) # create shareability graph (ExMAS)

28-02-23 14:21:52-INFO-Initializing pairwise trip shareability between 500 and 500 trips.
28-02-23 14:21:52-INFO-creating combinations
28-02-23 14:21:53-INFO-249500	 nR*(nR-1)
28-02-23 14:21:57-CRITICAL-LIFO pairs assertion failed
28-02-23 14:21:57-WARNING-Empty DataFrame
Columns: [origin_i, destination_i, ttrav_i, treq_i, delta_i, dist_i, VoT_i, origin_j, destination_j, ttrav_j, treq_j, delta_j, dist_j, VoT_j, i, j, t_oo, delay, delay_i, delay_j, t_od, t_dd, ttrav, kind, indexes, indexes_orig, indexes_dest, u_i, u_j, t_i, t_j, delta_ij, delta_ji, delta, u_pax]
Index: []

[0 rows x 35 columns]
28-02-23 14:21:57-WARNING-Empty DataFrame
Columns: [origin_i, destination_i, ttrav_i, treq_i, delta_i, dist_i, VoT_i, origin_j, destination_j, ttrav_j, treq_j, delta_j, dist_j, VoT_j, i, j, t_oo, delay, delay_i, delay_j, t_od, t_dd, ttrav, kind, indexes, indexes_orig, indexes_dest, u_i, u_j, t_i, t_j, delta_ij, delta_ji, delta, u_pax]
Index: []

[0 rows x 35 columns]
28-02-23 14:21:57-WARNING-Empty DataFrame
Columns: [origin_i, destination_i, ttrav_i, treq_i, delta_i, dist_i, VoT_i, origin_j, destination_j, ttrav_j, treq_j, delta_j, dist_j, VoT_j, i, j, t_oo, delay, delay_i, delay_j, t_od, t_dd, ttrav, kind, indexes, indexes_orig, indexes_dest, u_i, u_j, t_i, t_j, delta_ij, delta_ji, delta, u_pax]
Index: []

[0 rows x 35 columns]
28-02-23 14:21:57-WARNING-Empty DataFrame
Columns: [origin_i, destination_i, ttrav_i, treq_i, delta_i, dist_i, VoT_i, origin_j, destination_j, ttrav_j, treq_j, delta_j, dist_j, VoT_j, i, j, t_oo, delay, delay_i, delay_j, t_od, t_dd, ttrav, kind, indexes, indexes_orig, indexes_dest, u_i, u_j, t_i, t_j, delta_ij, delta_ji, delta, u_pax]
Index: []

[0 rows x 35 columns]
28-02-23 14:21:57-WARNING-Empty DataFrame
Columns: [origin_i, destination_i, ttrav_i, treq_i, delta_i, dist_i, VoT_i, origin_j, destination_j, ttrav_j, treq_j, delta_j, dist_j, VoT_j, i, j, t_oo, delay, delay_i, delay_j, t_od, t_dd, ttrav, kind, indexes, indexes_orig, indexes_dest, u_i, u_j, t_i, t_j, delta_ij, delta_ji, delta, u_pax]
Index: []

[0 rows x 35 columns]
28-02-23 14:21:58-INFO-Reduction of feasible pairs by 98.10%
28-02-23 14:21:58-INFO-Degree 2 	Completed

In [15]:
# Day-to-day simulation (incl. processing)
sim = Simulator(inData, params=params,
                    kpi_veh = D2D_veh_exp,
                    kpi_pax = d2d_kpi_pax,
                    f_driver_out = D2D_driver_out,
                    f_trav_out = d2d_no_request,
                    f_trav_mode = dummy_False,
                    logger_level=logging.WARNING)  # initialize

evol_micro = init_d2d_dotmap()
for day in range(params.get('nD', 1)):  # run iterations
    inData.passengers = mode_preday(inData, params)
    temp_rides = inData.sblts.rides.copy()
    temp_reqs = inData.sblts.requests.copy()
    
    rs_users = inData.passengers[(inData.passengers.mode_day == 'rs') | (inData.passengers.mode_day == 'pool')].index.tolist()
    poolers = inData.passengers[inData.passengers.mode_day == 'pool'].index.tolist()
    inData.sblts.rides = inData.sblts.rides[inData.sblts.rides.apply(lambda x: all(i in rs_users for i in x.indexes), axis=1)] # filter out all travellers opting for mode outside ride-hailing market
    inData.sblts.rides = inData.sblts.rides[inData.sblts.rides.apply(lambda x: (all(i in poolers for i in x.indexes) or x.kind == 1), axis=1)]  # filter out pooled trips for individuals opting for private ride
    inData.sblts.requests = inData.sblts.requests[inData.sblts.requests.apply(lambda x: x.pax_id in rs_users, axis=1)]
    abc = inData.sblts.rides.copy()
    defg = inData.sblts.requests.copy()
#     inData.sblts.requests = inData.sblts.requests[inData.sblts.requests.apply(lambda x: x.index in poolers, axis=1)]
    
    inData = prep_shared_rides(inData, params.shareability)  # prepare schedules
    sim.make_and_run(run_id=day)  # prepare and SIM
    sim.output()  # calc results
    sim.last_res = sim.res[day].copy()
    del sim.res[day]
    hij = inData.sblts.rides.copy()
    klm = inData.sblts.requests.copy()

    drivers_summary = update_d2d_drivers(sim=sim,params=params)
    travs_summary = update_d2d_travellers(sim=sim,params=params)
    
    exp_df = update_work_exp(inData, drivers_summary)
    inData.vehicles.work_exp = exp_df.work_exp
    inData.days_since_reg = exp_df.days_since_reg

    res_inf_driver = wom_driver(inData, params = params)
    inData.vehicles.informed = res_inf_driver
    inData.vehicles.expected_income = learning_unregist(inData, drivers_summary, params = params)
    
    res_regist = platform_regist(inData, drivers_summary, params = params)
    inData.vehicles.registered = res_regist.registered
    inData.vehicles.work_exp = res_regist.work_exp
    inData.vehicles.pos = fixed_supply.pos
    inData.vehicles.rejected_reg = res_regist.rejected_reg
    exp_inf_trav = travs_summary.loc[travs_summary.informed]
    average_xp_wait = exp_inf_trav.corr_xp_wait.mean() / 60
    res_inf_trav = wom_trav(inData, travs_summary, params = params)
    inData.passengers.informed = res_inf_trav.informed
    inData.passengers.expected_wait = res_inf_trav.perc_wait
    
    inData.sblts.rides = temp_rides.copy()
    inData.sblts.requests = temp_reqs.copy()
    
    evol_micro = d2d_summary_day(evol_micro, drivers_summary, travs_summary, day)

28-02-23 14:24:08-WARNING-Setting up 4h simulation at 2021-11-01 07:00:18 for 20 vehicles and 500 passengers in Delft, Netherlands
Chosen req: 0
Chosen req: 1
requests, id: 2, time: 27
Chosen req: 3
schedule triggered, id: 2, time: 72
requests, id: 4, time: 90
Chosen req: 5
Chosen req: 9
Chosen req: 10
Chosen req: 11
Chosen req: 12
schedule triggered, id: 4, time: 352
Chosen req: 16
requests, id: 21, time: 456
schedule triggered, id: 21, time: 456
Chosen req: 19
requests, id: 29, time: 719
schedule triggered, id: 29, time: 719
Chosen req: 20
requests, id: 32, time: 808
Chosen req: 14
Chosen req: 30
requests, id: 34, time: 910
schedule triggered, id: 34, time: 910
Chosen req: 15
Chosen req: 28
Chosen req: 26
schedule triggered, id: 32, time: 1016
Chosen req: 33
Chosen req: 41
Chosen req: 45
Chosen req: 48
requests, id: 52, time: 1414
schedule triggered, id: 52, time: 1414
Chosen req: 46
requests, id: 58, time: 1617
Chosen req: 51
Chosen req: 47
schedule triggered, id: 58, time: 1644
Chosen req: 50
Chosen req: 55
Chosen req: 53
requests, id: 64, time: 1881
requests, id: 66, time: 1895
Chosen req: 65
Chosen req: 61
schedule triggered, id: 64, time: 2013
Chosen req: 63
schedule triggered, id: 66, time: 2086
Chosen req: 62
Chosen req: 73
Chosen req: 70
requests, id: 76, time: 2246
Chosen req: 75
requests, id: 78, time: 2351
schedule triggered, id: 78, time: 2351
requests, id: 80, time: 2402
Chosen req: 77
schedule triggered, id: 80, time: 2421
requests, id: 82, time: 2432
schedule triggered, id: 82, time: 2432
Chosen req: 74
schedule triggered, id: 76, time: 2542
Chosen req: 79
Chosen req: 87
Chosen req: 91
requests, id: 93, time: 2870
requests, id: 94, time: 2877
Chosen req: 88
requests, id: 98, time: 3029
schedule triggered, id: 98, time: 3029
Chosen req: 96
Chosen req: 95
schedule triggered, id: 93, time: 3037
requests, id: 99, time: 3086
schedule triggered, id: 99, time: 3086
Chosen req: 97
Chosen req: 103
Chosen req: 104
Chosen req: 105
requests, id: 112, time: 3469
schedule triggered, id: 112, time: 3469
schedule triggered, id: 94, time: 3477
requests, id: 116, time: 3540
Chosen req: 111
schedule triggered, id: 116, time: 3581
requests, id: 119, time: 3640
schedule triggered, id: 119, time: 3640
Chosen req: 120
Chosen req: 110
requests, id: 125, time: 3823
Chosen req: 121
schedule triggered, id: 125, time: 3841
Chosen req: 108
requests, id: 127, time: 3903
schedule triggered, id: 127, time: 3903
Chosen req: 132
requests, id: 135, time: 4155
requests, id: 136, time: 4204
Chosen req: 126
Chosen req: 139
Chosen req: 134
Chosen req: 137
requests, id: 142, time: 4394
schedule triggered, id: 142, time: 4394
Chosen req: 129
schedule triggered, id: 136, time: 4489
requests, id: 148, time: 4575
requests, id: 150, time: 4620
schedule triggered, id: 150, time: 4620
Chosen req: 146
Chosen req: 143
requests, id: 156, time: 4711
schedule triggered, id: 156, time: 4711
schedule triggered, id: 135, time: 4755
Chosen req: 138
requests, id: 161, time: 4875
Chosen req: 154
Chosen req: 160
requests, id: 163, time: 4989
Chosen req: 166
Chosen req: 162
schedule triggered, id: 148, time: 5175
Chosen req: 175
requests, id: 178, time: 5303
schedule triggered, id: 178, time: 5303
Chosen req: 155
Chosen req: 168
Chosen req: 179
requests, id: 184, time: 5445
schedule triggered, id: 184, time: 5445
schedule triggered, id: 161, time: 5475
requests, id: 187, time: 5499
Chosen req: 172
requests, id: 188, time: 5530
schedule triggered, id: 188, time: 5530
requests, id: 191, time: 5574
Chosen req: 186
schedule triggered, id: 163, time: 5589
Chosen req: 182
requests, id: 196, time: 5738
requests, id: 197, time: 5738
schedule triggered, id: 196, time: 5738
Chosen req: 185
Chosen req: 173
Chosen req: 198
requests, id: 202, time: 5842
schedule triggered, id: 202, time: 5842
Chosen req: 180
schedule triggered, id: 197, time: 5899
requests, id: 203, time: 5963
requests, id: 204, time: 5967
Chosen req: 193
schedule triggered, id: 203, time: 6008
Chosen req: 189
Chosen req: 201
schedule triggered, id: 187, time: 6099
schedule triggered, id: 191, time: 6174
Chosen req: 194
schedule triggered, id: 204, time: 6198
Chosen req: 211
requests, id: 216, time: 6287
Chosen req: 213
schedule triggered, id: 216, time: 6302
Chosen req: 215
requests, id: 218, time: 6427
schedule triggered, id: 218, time: 6427
requests, id: 221, time: 6532
requests, id: 226, time: 6581
Chosen req: 225
Chosen req: 229
requests, id: 233, time: 6891
Chosen req: 232
schedule triggered, id: 233, time: 6892
Chosen req: 223
Chosen req: 224
schedule triggered, id: 226, time: 7075
Chosen req: 235
schedule triggered, id: 221, time: 7132
Chosen req: 238
Chosen req: 227
Chosen req: 240
requests, id: 242, time: 7302
requests, id: 248, time: 7384
At time 7530, req queue: [239, 241, 243, 244, 245, 246, 249, 250, 251]
Veh queue: [16]
Chosen req: 250
At time 7547, req queue: [239, 241, 243, 244, 245, 246, 249, 251]
Veh queue: [20]
Chosen req: 243
At time 7579, req queue: [239, 241, 244, 245, 246, 249, 251]
Veh queue: [7]
Chosen req: 239
schedule triggered, id: 242, time: 7579
At time 7662, req queue: [241, 244, 245, 246, 249, 251]
Veh queue: [14]
Chosen req: 251
requests, id: 257, time: 7718
requests, id: 258, time: 7718
schedule triggered, id: 257, time: 7718
At time 7726, req queue: [241, 244, 245, 246, 249]
Veh queue: [9]
Chosen req: 244
At time 7822, req queue: [241, 245, 246, 249, 259, 260, 261, 262, 263]
Veh queue: [4]
Chosen req: 262
requests, id: 267, time: 7880
At time 7932, req queue: [245, 246, 249, 259, 260, 261, 263, 264, 268]
Veh queue: [18]
Chosen req: 264
requests, id: 269, time: 7968
schedule triggered, id: 248, time: 7984
At time 8021, req queue: [249, 259, 260, 261, 263, 268, 271]
Veh queue: [20]
Chosen req: 261
requests, id: 272, time: 8042
Chosen req: 263
Chosen req: 273
schedule triggered, id: 267, time: 8203
Chosen req: 271
requests, id: 278, time: 8248
schedule triggered, id: 278, time: 8248
schedule triggered, id: 258, time: 8318
requests, id: 284, time: 8329
requests, id: 285, time: 8332
requests, id: 288, time: 8383
Chosen req: 279
Chosen req: 286
schedule triggered, id: 285, time: 8419
Chosen req: 281
Chosen req: 276
schedule triggered, id: 269, time: 8568
requests, id: 298, time: 8583
requests, id: 300, time: 8624
schedule triggered, id: 300, time: 8624
schedule triggered, id: 272, time: 8642
requests, id: 301, time: 8654
Chosen req: 289
schedule triggered, id: 301, time: 8805
Chosen req: 294
Chosen req: 296
schedule triggered, id: 288, time: 8877
Chosen req: 305
schedule triggered, id: 284, time: 8929
requests, id: 310, time: 8934
Chosen req: 297
Chosen req: 306
requests, id: 317, time: 9103
schedule triggered, id: 298, time: 9183
Chosen req: 299
Chosen req: 318
requests, id: 324, time: 9321
schedule triggered, id: 324, time: 9321
Chosen req: 303
schedule triggered, id: 310, time: 9360
Chosen req: 323
requests, id: 329, time: 9475
Chosen req: 311
Chosen req: 314
schedule triggered, id: 317, time: 9575
Chosen req: 333
Chosen req: 332
requests, id: 342, time: 9659
Chosen req: 336
requests, id: 349, time: 9833
requests, id: 351, time: 9847
requests, id: 352, time: 9852
schedule triggered, id: 352, time: 9852
Chosen req: 339
Chosen req: 355
schedule triggered, id: 351, time: 10005
Chosen req: 358
schedule triggered, id: 329, time: 10075
Chosen req: 347
schedule triggered, id: 349, time: 10092
requests, id: 359, time: 10104
schedule triggered, id: 359, time: 10104
Chosen req: 341
Chosen req: 335
requests, id: 364, time: 10190
requests, id: 366, time: 10248
schedule triggered, id: 342, time: 10259
Chosen req: 345
Chosen req: 365
requests, id: 374, time: 10421
Chosen req: 378
Chosen req: 363
requests, id: 379, time: 10486
schedule triggered, id: 379, time: 10486
Chosen req: 380
Chosen req: 369
schedule triggered, id: 374, time: 10717
schedule triggered, id: 364, time: 10790
Chosen req: 367
Chosen req: 373
schedule triggered, id: 366, time: 10848
requests, id: 389, time: 10877
Chosen req: 385
Chosen req: 382
requests, id: 391, time: 10971
schedule triggered, id: 391, time: 10971
Chosen req: 384
schedule triggered, id: 389, time: 11099
requests, id: 396, time: 11113
Chosen req: 398
Chosen req: 399
requests, id: 402, time: 11437
Chosen req: 394
requests, id: 405, time: 11540
Chosen req: 404
schedule triggered, id: 405, time: 11576
Chosen req: 400
Chosen req: 407
schedule triggered, id: 396, time: 11713
Chosen req: 403
requests, id: 408, time: 11814
schedule triggered, id: 408, time: 11814
Chosen req: 409
Chosen req: 411
schedule triggered, id: 402, time: 12037
Chosen req: 414
Chosen req: 412
Chosen req: 413
Chosen req: 420
Chosen req: 416
Chosen req: 424
Chosen req: 427
Chosen req: 422
requests, id: 438, time: 12819
requests, id: 442, time: 12874
requests, id: 443, time: 12891
requests, id: 445, time: 12902
requests, id: 447, time: 12943
Chosen req: 448
Chosen req: 433
Chosen req: 430
schedule triggered, id: 445, time: 13181
requests, id: 455, time: 13182
schedule triggered, id: 455, time: 13182
Chosen req: 441
requests, id: 458, time: 13312
Chosen req: 457
Chosen req: 460
requests, id: 462, time: 13407
schedule triggered, id: 438, time: 13419
requests, id: 464, time: 13450
schedule triggered, id: 464, time: 13450
requests, id: 467, time: 13473
schedule triggered, id: 467, time: 13473
schedule triggered, id: 442, time: 13474
requests, id: 469, time: 13483
schedule triggered, id: 443, time: 13491
Chosen req: 453
schedule triggered, id: 462, time: 13503
requests, id: 470, time: 13529
schedule triggered, id: 447, time: 13543
Chosen req: 465
schedule triggered, id: 470, time: 13569
Chosen req: 461
schedule triggered, id: 458, time: 13912
Chosen req: 478
requests, id: 482, time: 13953
Chosen req: 473
requests, id: 486, time: 14028
requests, id: 489, time: 14058
schedule triggered, id: 489, time: 14058
Chosen req: 476
schedule triggered, id: 486, time: 14077
schedule triggered, id: 469, time: 14083
Chosen req: 487
requests, id: 493, time: 14160
schedule triggered, id: 493, time: 14160
Chosen req: 492
Chosen req: 484
Chosen req: 497
schedule triggered, id: 482, time: 14553
Chosen req: 495
28-02-23 14:24:26-WARNING-day 0: simulation time 14.5 s
28-02-23 14:24:27-WARNING-assertion tests for simulation results - passed

In [16]:
evol_micro, evol_agg = d2d_agg_statistics(evol_micro, params) # multi-day stats

In [17]:
# Save d2d stats to zip file
with zipfile.ZipFile('evol.zip', 'w') as csv_zip:
    csv_zip.writestr("evol_agg_supply.csv", evol_agg.supply.to_csv())
    csv_zip.writestr("evol_agg_demand.csv", evol_agg.demand.to_csv())

In [18]:
evol_agg.supply

,inform,regist,rejected_reg,particip,reject_particip,mean_perc_inc,mean_perc_inc_ptcp,mean_perc_inc_reg,mean_exp_inc
day,,,,,,,,,
0,20,20,0,8,0,89.227317,77.47586,89.227317,0.29125

In [19]:
evol_agg.demand

,inform,requests,req_solo,req_pool,gets_offer_solo,gets_offer_pooling,mean_wait_solo,corr_mean_wait_solo,mean_wait_pooling,corr_mean_wait_pooling,perc_wait_solo,perc_wait_req,bike,car,pt
day,,,,,,,,,,,,,,,
0,500,348,152,196,96,143,1312.543933,1465.224138,1157.548117,1069.12069,212.6896,204.047126,127,25,0

In [ ]:
# Plot number of drivers and income
fig, axes = plt.subplots(nrows=5, ncols=1, figsize = (8,12.5), sharex = True)
evol_agg.supply[['inform','regist','particip']].plot(ax = axes[0], color=['lightsteelblue','tab:blue','midnightblue'])
axes[0].set_title('(A) Ridesourcing supply')
axes[0].legend(['Informed','Registered','Participating'])
axes[0].set_ylim([0,params.nV + 25])
axes[0].set_ylabel('Number of drivers')
evol_agg.supply[['mean_perc_inc','mean_exp_inc']].plot(ax = axes[2], color=['lightsteelblue','midnightblue'])
axes[2].set_title('(C) Driver earnings')
axes[2].legend(['Expected','Experienced'])
axes[2].set_ylim([0,math.ceil(max(evol_agg.supply.mean_perc_inc.max(),evol_agg.supply.mean_exp_inc.max())/50)*50])
axes[2].set_ylabel('Income (\u20ac)')


evol_agg.demand[['requests','bike','car','pt']].plot.area(ax = axes[1])
h,l = axes[1].get_legend_handles_labels()
evol_agg.demand['inform'].plot(ax = axes[1], color = 'black', linestyle = 'dashed', label = 'informed')
line = Line2D([0], [0],color='black', linestyle ='dashed')
axes[1].set_title('(B) Demand')
axes[1].set_ylim([0,len(inData.passengers) * 1.1])
axes[1].set_ylabel('Number of travellers')
h.extend([line])
axes[1].legend(labels=["Ridesourcing","Bike","Car","Public transport","Informed"], handles=h)

ax_sec = axes[3].twinx()
evol_agg.demand['proport_match'] = evol_agg.demand.gets_offer / evol_agg.demand.requests * 100
evol_agg.demand['mean_wait'].apply(lambda x: 1/60 * x).plot(ax = axes[3], label='Experienced waiting time', color ='lightsalmon')
evol_agg.demand['corr_mean_wait'].apply(lambda x: 1/60 * x).plot(ax = axes[3], label='Corrected exp. waiting time', color ='rosybrown')
evol_agg.demand['perc_wait'].apply(lambda x: 1/60 * x).plot(ax = axes[3], label='Expected waiting time', color ='tomato')
evol_agg.demand['proport_match'].plot(ax = ax_sec, color = 'grey', label='Share of requests returned with offer', linestyle = 'dotted')
lines_1, labels_1 = axes[3].get_legend_handles_labels()
lines_2, labels_2 = ax_sec.get_legend_handles_labels()
lines = lines_1 + lines_2
labels = labels_1 + labels_2
axes[3].legend(lines, labels, loc=0)
axes[3].set_title('(D) Level of service')
axes[3].set_ylabel('Mean wait. time (min)')
ax_sec.set_ylabel('Request success')
ax_sec.yaxis.set_major_formatter(mtick.PercentFormatter())
max_val = max(evol_agg.demand.mean_wait.max(),evol_agg.demand.corr_mean_wait.max(),evol_agg.demand.perc_wait.max())
axes[3].set_ylim([0,math.ceil((1/60)*max_val/2)*2+0.5])
ax_sec.set_ylim([0,100+5])
ax_sec.grid(None)

proport_rs = evol_agg.demand.requests / evol_agg.demand.inform * 100 
proport_rs.plot(ax = axes[4], label = 'Travellers - Mode share of ridesourcing', color='maroon')
axes[4].set_title('(E) Platform utilisation')
axes[4].set_ylim([0,100+2])
axes[4].set_ylabel('Platform utilisation')

axes[4].yaxis.set_major_formatter(mtick.PercentFormatter())

proport_work = evol_agg.supply.particip / evol_agg.supply.regist * 100
proport_work.plot(ax = axes[4], label = 'Drivers - Labour participation rate', color ='midnightblue')
lines, labels = axes[4].get_legend_handles_labels()
axes[4].legend(labels)

plt.savefig('d2d-evo.png')

---

In [ ]:
inData.keys()

In [ ]:
# inData.pt_itinerary.to_csv('inData_pt-itinerary.csv')
inData.vehicles

In [ ]:
inData.stats.center

In [ ]:
evol_micro.supply.inform

In [ ]:
inData.skim.iloc[:20, :20].to_csv('inData_skim.csv')

In [ ]:
(evol_micro.demand.gets_offer * evol_micro.demand.requests).sum()

In [ ]:
inData.passengers.to_csv('inData_passengers.csv')

In [ ]:
evol_micro.demand.gets_offer

In [ ]:
inData.vehicles

In [ ]:
# sim.last_res.pax_exp.head(50).to_csv('pax_exp.csv')
sim.last_res.keys()

In [ ]:
# sim.last_res.veh_kpi.head(50).to_csv('veh_kpi.csv')
sim.last_res.veh_exp

In [ ]:
sim.last_res.pax_exp

In [ ]:
import networkx as nx
df = nx.to_pandas_edgelist(inData.G)
df.to_csv('edges.csv')

In [ ]:
inData.pt_itinerary

In [ ]:
abc

In [ ]:
defg

In [ ]:
inData.keys()

In [ ]:
inData.sblts.keys()

In [ ]:
inData.sblts.requests

In [ ]:
inData.the_skim.sort_index().sort_index(axis=1).head(20)

In [ ]:
inData.sblts.requests

In [ ]:
inData.sblts.R[2]

In [ ]:
inData.sblts.rides

In [ ]:
inData.sblts.requests

In [ ]:
sim.runs[0]['trips'][sim.runs[0]['trips']['pax'] == 1722]

In [ ]:
inData.requests[inData.requests['pax_id'] == 1722]['sim_schedule']

In [ ]:
inData.requests.loc[439].sim_schedule

In [ ]:
# inData.requests.loc[421]
inData.requests.loc[13].sim_schedule

In [ ]:
inData.keys()

In [ ]:
inData.sblts.keys()

In [ ]:
inData.sblts.rides[inData.sblts.rides.selected == 1].tail(110)

In [ ]:
inData.sblts.requests.loc[21]

In [ ]:
sim.runs[1].rides

In [ ]:
sim.runs[0].rides[sim.runs[0].rides['event']=='DEPARTS_FROM_PICKUP'].head(50)

In [ ]:
# sim.runs[0].rides[sim.runs[0].rides['t']>=4000].head(50)
sim.runs[0].rides.head(50)

In [ ]:
sim.runs[0].trips[sim.runs[0].trips['pax']==19]

In [ ]:
inData.sblts.schedule['sim_schedule']

In [ ]:
inData.requests['sim_schedule'].head(50)

In [ ]:
inData.requests.sim_schedule.loc[20]

In [ ]:
inData.keys()

In [ ]:
inData.vehicles

In [ ]:
inData.passengers

In [ ]:
sim.runs[0].rides.head(50)

In [ ]:
sim.runs[0].trips[sim.runs[0].trips['pax']==257]

In [ ]:
inData.keys()

In [ ]:
inData.sblts.keys()

In [ ]:
inData.sblts.requests.head(50)

In [ ]:
inData.sblts.schedule.head(70)

In [ ]:
inData.requests

In [ ]:
inData.requests.loc[407].sim_schedule

In [ ]:
inData.sblts.SINGLES

In [ ]:
inData.passengers.loc[201]

In [ ]:
inData.sblts.requests.loc[201]

In [ ]:
inData.sblts.rides

In [ ]:
inData.passengers[inData.passengers.mode_day == 'pool'].index.tolist()

In [ ]:
# inData.sblts.rides[inData.sblts.rides.apply(lambda x: any(i in pool for i in x.indexes))]
pool=[2,5]
inData.sblts.rides.apply(lambda x: any(i in pool for i in x.indexes), axis=1)

In [ ]:
inData.passengers.loc[422]

In [ ]:
inData.sblts.requests

In [ ]:
inData.sblts.schedule.head(50)

In [ ]:
travs_summary

In [ ]:
evol_micro.demand.wait_time

In [ ]:
evol_micro.demand.corr_wait_time

In [ ]:
evol_micro.demand.req_pool

In [ ]:
evol_micro.demand.perc_wait

In [ ]:
sim.runs[2].trips.head(50)

In [ ]:
inData.sblts.rides.head(90)

In [ ]:
inData.sblts.requests.loc[453]

In [ ]:
xyz = inData.sblts.rides[inData.sblts.rides.apply(lambda x: all(i in rs_users for i in x.indexes), axis=1)] # filter out all travellers opting for mode outside ride-hailing market
xyz = xyz[xyz.apply(lambda x: (all(i in poolers for i in x.indexes) or x.kind == 1), axis=1)]  # filter out pooled trips for individuals opting for private ride

xyz
# poolers

In [35]:
inData.sblts.schedule.tail(50)

,indexes,u_pax,u_veh,kind,u_paxes,times,indexes_orig,indexes_dest,index,lambda_r,PassHourTrav_ns,row,selected,degree,nodes,req_id,sim_schedule
6611,"[444, 447]",6.65650,250,21,"[3.2359, 3.4206000000000003]","[12916.0, 3, 42, 205]","[444, 447]","[447, 444]",6611,-2.521127,71,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 672526443, 6248301254, 44844070, 126911...","[None, 444, 447, 447, 444]",node time req_id od 0 ...
6643,"[426, 438]",7.17820,442,21,"[4.47585, 2.70235]","[12589.0, 274, 32, 136]","[426, 438]","[438, 426]",6643,-5.696970,66,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44739628, 1474883280, 44859610, 1383461...","[None, 426, 438, 438, 426]",node time req_id od 0 ...
6673,"[74, 76]",6.25795,247,21,"[3.4302, 2.82775]","[2190.0, 61, 35, 151]","[74, 76]","[76, 74]",6673,-2.686567,67,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44877771, 44891423, 4124549374, 1391531...","[None, 74, 76, 76, 74]",node time req_id od 0 ...
6731,"[363, 379]",7.66780,489,21,"[5.0988, 2.569]","[10209.0, 253, 31, 205]","[363, 379]","[379, 363]",6731,-5.791667,72,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 2670677182, 7399789770, 1830076520, 139...","[None, 363, 379, 379, 363]",node time req_id od 0 ...
6738,"[211, 218]",6.10605,451,21,"[4.013375, 2.092675]","[6244.5, 141, 24, 286]","[211, 218]","[218, 211]",6738,-7.673077,52,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44837765, 1435362502, 1552651408, 14027...","[None, 211, 218, 218, 211]",node time req_id od 0 ...
6775,"[318, 324]",6.94240,216,21,"[3.1380749999999997, 3.8043250000000004]","[9169.5, 108, 46, 62]","[318, 324]","[324, 318]",6775,-1.918919,74,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44840841, 2323108138, 1433962926, 14027...","[None, 318, 324, 324, 318]",node time req_id od 0 ...
6830,"[180, 197]",8.28950,441,21,"[4.937950000000001, 3.35155]","[5373.0, 364, 42, 35]","[180, 197]","[197, 180]",6830,-4.188235,85,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44753493, 44850245, 44830592, 1410536895]","[None, 180, 197, 197, 180]",node time req_id od 0 ...
6955,"[224, 226]",9.61405,605,21,"[6.7637, 2.85035]","[6427.0, 286, 29, 290]","[224, 226]","[226, 224]",6955,-6.469136,81,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 582000012, 44814387, 44795688, 1433962853]","[None, 224, 226, 226, 224]",node time req_id od 0 ...
7231,"[70, 82]",8.11155,335,21,"[5.5146500000000005, 2.5969]","[2227.0, 61, 25, 249]","[70, 82]","[82, 70]",7231,-3.589041,73,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 527378782, 2323108159, 1552650472, 1448...","[None, 70, 82, 82, 70]",node time req_id od 0 ...
7254,"[263, 278]",7.63965,485,21,"[5.561875000000001, 2.077775]","[7835.5, 370, 24, 91]","[263, 278]","[278, 263]",7254,-5.830986,71,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1519889961, 44814387, 44851133, 1448535...","[None, 263, 278, 278, 263]",node time req_id od 0 ...
7293,"[63, 66]",6.49435,334,21,"[4.276675, 2.2176750000000003]","[1744.5, 227, 24, 83]","[63, 66]","[66, 63]",7293,-4.661017,59,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 5327428579, 44862225, 4300758655, 15084...","[None, 63, 66, 66, 63]",node time req_id od 0 ...
7317,"[392, 396]",6.44545,323,21,"[4.613700000000001, 1.8317500000000002]","[11031.0, 48, 21, 254]","[392, 396]","[396, 392]",7317,-4.046875,64,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1436427174, 1413911044, 1552650711, 151...","[None, 392, 396, 396, 392]",node time req_id od 0 ...
7326,"[137, 150]",7.45535,450,21,"[4.7141, 2.74125]","[4237.0, 394, 34, 22]","[137, 150]","[150, 137]",7326,-5.164384,73,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44852056, 1433963021, 1510591475, 15198...","[None, 137, 150, 150, 137]",node time req_id od 0 ...
7356,"[48, 52]",8.80795,732,21,"[6.43095, 2.3770000000000002]","[1245.0, 259, 25, 448]","[48, 52]","[52, 48]",7356,-9.764706,68,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1568976634, 4554554060, 1402734605, 153...","[None, 48, 52, 52, 48]",node time req_id od 0 ...
7369,"[430, 445]",5.66930,435,21,"[3.9316000000000004, 1.7377]","[12755.0, 131, 21, 283]","[430, 445]","[445, 430]",7369,-7.700000,50,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 617806644, 4095856086, 312033061, 15526...","[None, 430, 445, 445, 430]",node time req_id od 0 ...
7401,"[476, 486]",5.87205,356,21,"[3.4522500000000003, 2.4198]","[13878.0, 131, 29, 196]","[476, 486]","[486, 476]",7401,-5.472727,55,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4244308801, 1569647891, 44845664, 15526...","[None, 476, 486, 486, 476]",node time req_id od 0 ...
7482,"[182, 202]",5.76020,185,21,"[3.3382500000000004, 2.42195]","[5572.0, 95, 22, 68]","[182, 202]","[202, 182]",7482,-2.854167,48,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 3377240325, 44811247, 1854067403, 15696...","[None, 182, 202, 202, 182]",node time req_id od 0 ...
7494,"[88, 98]",6.64070,415,21,"[4.340775000000001, 2.299925]","[2811.5, 121, 24, 270]","[88, 98]","[98, 88]",7494,-6.545455,55,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 912615771, 44840845, 44791815, 1569975197]","[None, 88, 98, 98, 88]",node time req_id od 0 ...
7645,"[181, 187]",4.33175,216,21,"[2.5625750000000003, 1.7691750000000002]","[5382.5, 113, 22, 81]","[181, 187]","[187, 181]",7645,-3.909091,44,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1436427122, 44858614, 44823646, 1576740...","[None, 181, 187, 187, 181]",node time req_id od 0 ...
7697,"[460, 464]",5.03620,202,21,"[2.74955, 2.28665]","[13332.0, 134, 28, 40]","[460, 464]","[464, 460]",7697,-2.811321,53,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44815349, 1569646643, 44753928, 1584013...","[None, 460, 464, 464, 460]",node time req_id od 0 ...
7794,"[260, 272]",9.23070,487,21,"[5.336725, 3.8939749999999997]","[7790.5, 205, 47, 235]","[260, 272]","[272, 260]",7794,-4.411111,90,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4249122117, 2177111543, 44735538, 16089...","[None, 260, 272, 272, 260]",node time req_id od 0 ...
7828,"[434, 442]",10.55885,415,21,"[6.067925000000001, 4.490925]","[12660.5, 339, 50, 26]","[434, 442]","[442, 434]",7828,-3.029126,103,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4502921354, 44892459, 1608998231, 16089...","[None, 434, 442, 442, 434]",node time req_id od 0 ...
7836,"[146, 156]",4.93045,235,21,"[2.6942500000000003, 2.2362]","[4551.0, 145, 27, 63]","[146, 156]","[156, 146]",7836,-3.700000,50,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1563023404, 4810005054, 44798266, 16208...","[None, 146, 156, 156, 146]",node time req_id od 0 ...
7931,"[433, 455]",5.49990,389,21,"[3.6144000000000003, 1.8855]","[12848.0, 264, 20, 105]","[433, 455]","[455, 433]",7931,-7.840909,44,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 7003131561, 44778412, 44813101, 1679761...","[None, 433, 455, 455, 433]",node time req_id od 0 ...
8014,"[175, 184]",7.15565,267,21,"[3.8042, 3.35145]","[5318.0, 17, 37, 213]","[175, 184]","[184, 175]",8014,-2.926471,68,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 248191377, 2381861250, 44844068, 229673...","[None, 175, 184, 184, 175]",node time req_id od 0 ...
8018,"[194, 204]",7.36610,536,21,"[5.0329500000000005, 2.33315]","[5603.0, 395, 28, 113]","[194, 204]","[204, 194]",8018,-7.121212,66,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1668136731, 1830058778, 839335227, 2296...","[None, 194, 204, 204, 194]",node time req_id od 0 ...
8067,"[384, 389]",9.75870,483,21,"[6.2398750000000005, 3.518825]","[10565.5, 401, 40, 42]","[384, 389]","[389, 384]",8067,-4.193548,93,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 3669180604, 1552650403, 44721739, 23818...","[None, 384, 389, 389, 384]",node time req_id od 0 ...
8147,"[277, 284]",9.59765,402,21,"[6.0831, 3.5145500000000003]","[8225.0, 95, 44, 263]","[277, 284]","[284, 277]",8147,-2.865385,104,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 6960779679, 1570983366, 568743900, 2599...","[None, 277, 284, 284, 277]",node time req_id od 0 ...
8153,"[291, 298]",6.82835,185,21,"[4.133900000000001, 2.6944500000000002]","[8438.0, 121, 33, 31]","[291, 298]","[298, 291]",8153,-1.402597,77,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44744586, 44777528, 1371031395, 2599554...","[None, 291, 298, 298, 291]",node time req_id od 0 ...
8183,"[26, 32]",6.03700,261,21,"[3.558525, 2.478475]","[656.5, 96, 28, 137]","[26, 32]","[32, 26]",8183,-3.423729,59,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 610983540, 1413911135, 44834050, 263562...","[None, 26, 32, 32, 26]",node time req_id od 0 ...
8199,"[168, 188]",7.27965,211,21,"[3.87695, 3.4027000000000003]","[5223.0, 171, 36, 4]","[168, 188]","[188, 168]",8199,-2.057971,69,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4228809539, 1679761155, 4986579661, 267...","[None, 168, 188, 188, 168]",node time req_id od 0 ...
8212,"[96, 99]",5.82675,93,21,"[3.18615, 2.6406]","[2987.0, 33, 30, 30]","[96, 99]","[99, 96]",8212,-0.453125,64,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1608998294, 1510592095, 4554554060, 315...","[None, 96, 99, 99, 96]",node time req_id od 0 ...
8286,"[85, 94]",5.74290,272,21,"[3.82515, 1.9177499999999998]","[2659.0, 196, 23, 53]","[85, 94]","[94, 85]",8286,-3.689655,58,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44793238, 1433963031, 4300758655, 35810...","[None, 85, 94, 94, 85]",node time req_id od 0 ...
8297,"[345, 342]",4.96825,221,21,"[3.0161750000000005, 1.952075]","[9651.5, 102, 20, 99]","[345, 342]","[342, 345]",8297,-4.022727,44,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1391531777, 5509265887, 1576740176, 358...","[None, 345, 342, 342, 345]",node time req_id od 0 ...
8421,"[429, 443]",5.51820,204,21,"[3.11515, 2.40305]","[12768.0, 83, 28, 93]","[429, 443]","[443, 429]",8421,-2.578947,57,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 7229895331, 44846551, 1413910854, 41591...","[None, 429, 443, 443, 429]",node time req_id od 0 ...
8459,"[355, 359]",6.89505,371,21,"[4.225300000000001, 2.66975]","[9961.0, 145, 33, 193]","[355, 359]","[359, 355]",8459,-4.300000,70,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1436427208, 44835830, 5264539952, 42464...","[None, 355, 359, 359, 355]",node time req_id od 0 ...
8483,"[350, 364]",7.57325,437,21,"[5.072225, 2.5010250000000003]","[9870.5, 288, 30, 119]","[350, 364]","[364, 350]",8483,-4.986301,73,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 30016728, 4124549374, 1575265196, 42667...","[None, 350, 364, 364, 350]",node time req_id od 0 ...
8519,"[30, 34]",7.63555,310,21,"[4.984850000000001, 2.6507]","[785.0, 79, 31, 200]","[30, 34]","[34, 30]",8519,-2.924051,79,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1519889905, 253143148, 3377240345, 4407...","[None, 30, 34, 34, 30]",node time req_id od 0 ...
8526,"[61, 64]",6.31895,355,21,"[3.7036750000000005, 2.615275]","[1683.5, 238, 31, 86]","[61, 64]","[64, 61]",8526,-4.916667,60,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 643587012, 44732933, 4261100545, 443894...","[None, 61, 64, 64, 61]",node time req_id od 0 ...
8553,"[473, 489]",9.34915,602,21,"[6.38035, 2.9688]","[13687.0, 445, 34, 123]","[473, 489]","[489, 473]",8553,-6.166667,84,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1830058806, 1402734973, 1436427064, 448...","[None, 473, 489, 489, 473]",node time req_id od 0 ...
8653,"[347, 349]",10.96030,312,21,"[5.935675000000001, 5.024625]","[9700.5, 216, 59, 37]","[347, 349]","[349, 347]",8653,-1.666667,117,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 5052031931, 44785116, 4986579678, 49865...","[None, 347, 349, 349, 347]",node time req_id od 0 ...
8706,"[219, 221]",6.72200,283,21,"[4.4005, 2.3215]","[6409.0, 150, 28, 105]","[219, 221]","[221, 219]",8706,-3.042857,70,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1774593290, 1608998194, 44814382, 51197...","[None, 219, 221, 221, 219]",node time req_id od 0 ...
8782,"[339, 351]",6.06445,355,21,"[3.9453000000000005, 2.1191500000000003]","[9627.0, 212, 26, 117]","[339, 351]","[351, 339]",8782,-5.016949,59,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4968645019, 44829651, 620833182, 517187...","[None, 339, 351, 351, 339]",node time req_id od 0 ...
8847,"[273, 267]",8.50480,338,21,"[5.4274000000000004, 3.0774]","[7847.0, 254, 28, 56]","[273, 267]","[267, 273]",8847,-3.760563,71,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4798458420, 44859966, 44834678, 5172033...","[None, 273, 267, 267, 273]",node time req_id od 0 ...
8866,"[186, 196]",5.00305,336,21,"[3.2752, 1.72785]","[5521.0, 186, 20, 130]","[186, 196]","[196, 186]",8866,-6.636364,44,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 311106487, 44804961, 44763124, 5264539946]","[None, 186, 196, 196, 186]",node time req_id od 0 ...
8906,"[354, 366]",6.93720,536,21,"[4.497025000000001, 2.440175]","[9945.5, 287, 30, 219]","[354, 366]","[366, 354]",8906,-7.786885,61,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 4249122117, 2587864260, 1584562931, 531...","[None, 354, 366, 366, 354]",node time req_id od 0 ...
8948,"[232, 233]",5.69155,189,21,"[3.699275, 1.992275]","[6863.5, 15, 24, 150]","[232, 233]","[233, 232]",8948,-2.048387,62,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1608998292, 1608998282, 3377240345, 575...","[None, 232, 233, 233, 232]",node time req_id od 0 ...
8952,"[134, 142]",6.13380,237,21,"[3.257575, 2.876225]","[4224.5, 62, 31, 144]","[134, 142]","[142, 134]",8952,-3.232143,56,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44820494, 44812871, 44847928, 6884767739]","[None, 134, 142, 142, 134]",node time req_id od 0 ...
9056,"[193, 203]",9.54210,714,21,"[6.724825000000001, 2.817275]","[5721.5, 146, 31, 537]","[193, 203]","[203, 193]",9056,-8.037975,79,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 1569647777, 1410536856, 44897956, 84639...","[None, 193, 203, 203, 193]",node time req_id od 0 ...
9084,"[105, 119]",7.46095,305,21,"[4.5942, 2.86675]","[3406.0, 167, 33, 105]","[105, 119]","[119, 105]",9084,-3.066667,75,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,2,"[None, 44852767, 3581094279, 1830058797, 84639...","[None, 105, 119, 119, 105]",node time req_id od 0 ...

In [41]:
inData.requests.loc[489]

pax_id                                                         489
origin                                                  1402734973
destination                                             1436427064
treq                                           2021-11-01 10:54:36
tdep                                                           NaN
ttrav                                              0 days 00:05:40
tarr                                           2021-11-01 11:00:16
tdrop                                                          NaN
shareable                                                     True
schedule_id                                                    NaN
dist                                                          3404
car_park_cost                                                  7.5
dest_center                                                  False
platform                                                         0
ride_id                                                       8553
position                                                         1
sim_schedule                node time  req_id    od
0          ...
Name: 489, dtype: object

In [ ]:
inData.requests.loc[256].sim_schedule

In [ ]:
inData.passengers.loc[256]

In [ ]:
inData.sblts.rides

In [ ]:
abc

In [ ]:
inData.sblts.schedule.loc[9084].sim_schedule

In [ ]:
inData.sblts.schedule.tail(50)

In [ ]:
inData.passengers.loc[256]

In [ ]:
hij

In [ ]:
klm

In [36]:
sim.runs[0].trips[sim.runs[0].trips.pax == 473]

   pax         pos      t                   event  veh_id
0  473  1830058806      0              STARTS_DAY     NaN
1  473  1830058806  13761           REQUESTS_RIDE     NaN
2  473  1830058806  13977          RECEIVES_OFFER     NaN
3  473  1830058806  13977           ACCEPTS_OFFER     NaN
4  473  1830058806  13997       ARRIVES_AT_PICKUP    20.0
5  473  1830058806  14182  MEETS_DRIVER_AT_PICKUP    20.0
6  473  1830058806  14212     DEPARTS_FROM_PICKUP    20.0
7  473  4486831034  15160      ARRIVES_AT_DROPOFF    20.0
8  473  4486831034  15170       SETS_OFF_FOR_DEST     NaN
9  473  4486831034  15170         ARRIVES_AT_DEST     NaN

In [ ]:
sim.runs[0].trips[sim.runs[0].trips.pax == 193]

In [ ]:
sim.runs[2].rides[sim.runs[2].rides.veh == 6].tail(100)

In [ ]:
sim.runs[2].rides[sim.runs[2].rides.apply(lambda x: x.paxes == [119], axis=1)]

In [ ]:
inData.sblts.schedule.loc[9057].sim_schedule

In [ ]:
klm.loc[119]

In [ ]:
hij.loc[9084].

In [ ]:
inData.sblts.schedule.loc[9084]

In [ ]:
koekoek = inData.requests.copy()
koekoek['hoi'] = inData.sblts.requests.shareable
koekoek

In [ ]:
inData.sblts.requests.loc[259]

In [ ]:
koekoek.hoi.fillna(False)

In [ ]:
travs_summary.loc[463]

In [ ]:
sim.last_res.pax_exp.loc[463]

In [ ]:
(inData.requests.loc[378].treq - params.t0).seconds

In [ ]:
evol_micro.supply

In [ ]:
sim.runs[0].outcomes

In [23]:
abc = travs_summary[travs_summary.chosen_mode == 'pool']
abc[abc.gets_offer]

,orig,dest,t_req,tt_min,dist,informed,requests,gets_offer,accepts_offer,xp_wait,xp_ivt,xp_ops,act_shared,xp_discount,xp_tt_total,init_perc_wait,corr_xp_wait,new_perc_wait,chosen_mode
pax,,,,,,,,,,,,,,,,,,,
2,4053473202,1385072823,2021-11-01 07:00:45,0 days 00:04:01,2416,True,True,True,True,496.0,241.0,55.0,9999,1.0,792.0,4.6,496.0,102.88,pool
3,44862225,44759522,2021-11-01 07:01:15,0 days 00:06:38,3983,True,True,True,True,211.0,585.0,55.0,9999,1.0,851.0,0.0,211.0,42.20,pool
4,1679761151,44839603,2021-11-01 07:01:48,0 days 00:03:32,2125,True,True,True,True,755.0,212.0,55.0,9999,1.0,1022.0,21.8,755.0,168.44,pool
5,2381851915,44841824,2021-11-01 07:02:03,0 days 00:06:26,3866,True,True,True,True,59.0,777.0,55.0,9999,1.0,891.0,1.2,59.0,12.76,pool
11,1552650415,44734726,2021-11-01 07:05:54,0 days 00:06:10,3703,True,True,True,True,304.0,465.0,55.0,9999,1.0,824.0,39.6,304.0,92.48,pool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,4244308801,1552650539,2021-11-01 10:51:17,0 days 00:04:27,2678,True,True,True,True,353.0,665.0,40.0,9999,1.0,1058.0,110.0,353.0,158.60,pool
478,1435362418,27082148,2021-11-01 10:52:06,0 days 00:07:05,4253,True,True,True,True,266.0,914.0,40.0,9999,1.0,1220.0,27.0,266.0,74.80,pool
486,1569647891,44845664,2021-11-01 10:54:06,0 days 00:04:58,2980,True,True,True,True,355.0,298.0,40.0,9999,1.0,693.0,0.0,355.0,71.00,pool
489,1402734973,1436427064,2021-11-01 10:54:36,0 days 00:05:40,3404,True,True,True,True,14566.0,340.0,40.0,9999,1.0,14946.0,2698.0,14566.0,5071.60,pool
493,44789407,44891909,2021-11-01 10:56:18,0 days 00:05:29,3290,True,True,True,True,14266.0,329.0,40.0,9999,1.0,14635.0,0.0,14266.0,2853.20,pool

In [31]:
travs_summary.loc[489]

orig                       1402734973
dest                       1436427064
t_req             2021-11-01 10:54:36
tt_min                0 days 00:05:40
dist                             3404
informed                         True
requests                         True
gets_offer                       True
accepts_offer                    True
xp_wait                         14566
xp_ivt                            340
xp_ops                             40
act_shared                       9999
xp_discount                         1
xp_tt_total                     14946
init_perc_wait                   2698
corr_xp_wait                    14566
new_perc_wait                  5071.6
chosen_mode                      pool
Name: 489, dtype: object